### ISSUE TITLE
More documentation on ELB integration needed

### ISSUE THREAD

**Issue by mudrd8mz** [brendanheywood/moodle-tool_heartbeat#1]
The clean out-of-the-box installation throws 503 unless the elb.test file is prepared. Currently, I am missing more documentation on how the tool is supposed to be actually integrated with http://aws.amazon.com/elasticloadbalancing/

**Comment by brendanheywood** [comment]
I've now automated this check so it tests writing to sitedata and then tests reading from it, so no setup is required at all.
