### ISSUE TITLE
Doesn't work for Totara 2.6

### ISSUE THREAD

**Issue by ilya-catalyst** [brendanheywood/moodle-tool_heartbeat#11]
!!! Plugin "tool_heartbeat" (2016111001) could not be installed.  It requires a newer version of Moodle (currently you are using 2013111811, you need 2014050800). !!!
11:28:31.670 !! 
11:28:31.671 Error code: pluginrequirementsnotmet !!
11:28:31.671 !! Stack trace: * line 461 of /lib/upgradelib.php: upgrade_requires_exception thrown
11:28:31.671 * line 1608 of /lib/upgradelib.php: call to upgrade_plugins()
11:28:31.671 * line 492 of /lib/installlib.php: call to upgrade_noncore()
11:28:31.671 * line 409 of /lib/phpunit/classes/util.php: call to install_cli_database()
11:28:31.671 * line 153 of /admin/tool/phpunit/cli/util.php: call to phpunit_util::install_site()
11:28:31.671  !!
11:28:31.672

**Comment by brendanheywood** [comment]
Ok the code *should* actually work in old moodles, so I've just fixed up the version file to allow it to be installed.
